alias     ls='ls -lGh'
alias     la='ls -lGa'
alias     lt='ls -lGtar'
alias     cp='cp -r'
alias    scp='scp -r'
alias     em='emacs'
alias     le='less'
alias     cb='pbcopy'
alias     bc='pbpaste'
alias    ssh='ssh -Y'
alias     ka='killall'
alias     k9='kill -9'
alias      d='cd'
alias    cdv='cd $WD'
alias     tl='tail'
alias     tf='tail -f'
alias    tfl='tail -f logfile'
alias     gr='grep -Irni --color=tty'
alias     ..='cd ..'
alias     tm='tmux -new'
alias     bu='brew upgrade; brew update'
alias   bdep='brew deps --tree'
alias matlab='/Applications/MATLAB_R2017b.app/bin/matlab -nodesktop'
alias  julia='/Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia'
#. $HOME/Downloads/z-master/z.sh