#!/bin/bash

# util
alias   rmfr=`rm -fr`
alias     cp='cp -r'
alias    scp='scp -r'
alias    ssh='ssh -Y'
alias     ..='cd ..'
alias     dc='cd -'
alias    cdn='cd $NEK_WD; s'
alias    cdm='cd $HOME/matlab; s'
alias    cdp='cd $HOME/python; s'
alias     kk='kill'
alias     ka='killall'
alias     k9='kill -9'
alias     tc='tar -cvf'  # create
alias     tx='tar -xvf'  # extract
alias     hn='head -n'
alias    hn1='head -n 1'
alias whereami='hostname'
# 
alias       pv='paraview'
# 
alias     nv="nvim"
alias     sx="sxiv -b"
alias     ok="okular"
alias     em='emacs -nw'
alias     tm='tmux -new'
alias     ts='tmux ls'
alias   mtlb='$MTLB_BIN/matlab -nodesktop'
alias     qs='qstat  -u $(whoami)' 
alias     sq='squeue -u $(whoami)' 
alias     tf='tail -f'
alias     le='less'
alias    lel='less logfile'
# git
alias     gs='git status'
alias     ga='git add'
alias    gau='git add -u'
alias     gp='git push'
alias     up='git push --set-upstream'
alias     gc='git commit'
alias    gcm='git commit -m'
alias    gco='git checkout'
alias     gb='git branch'
alias     gd='git diff'
alias    gdf='git difftool'
# conda
alias     ca='conda activate'
alias    cde='conda deactivate'
# screen
alias    sls='screen -ls'
alias    sdr='screen -dr'
#. $HOME/Downloads/z-master/z.sh
# Julia
alias     jl='julia --proj'
alias     jj='julia +beta --proj'
alias   jlts='julia +lts --proj'
alias    jup='juliaup'

case `uname` in
Darwin)
	# util
	alias      s='ls -lh  -G'
	alias     la='ls -lA  -G'
	alias     lt='ls -ltr -G'
	alias    cdv='cd $HOME/vedant; s'
    alias    cdg='cd $HOME/Google\ Drive; s'
    alias    cdc='cd $HOME/cmu; s'
    alias    cdd='cd $HOME/Downloads; s'
    alias    cdr='cd $HOME/read; s'
	# osx
    alias   disp='open /System/Library/PreferencePanes/Displays.prefPane'
    alias   opcr='open -a /Applications/Google\ Chrome.app/'
    # brew
    alias     bu='brew upgrade; brew update'
    alias   bdep='brew deps --tree'
	;;
Linux)
	# util
	alias  s='ls -lh  --color=tty'
	alias la='ls -lA  --color=tty'
	alias lt='ls -ltr --color=tty'
	;;
esac
