#!/bin/bash

# PS1
export PS1='[\[\e[0;32m\]$ME\[\e[1;36m\]@$MACHINE\[\e[0m\] \W]:'

# misc scripts
export PATH=$HOME/bin:$PATH

## vars
export email="vedantpuri@gmail.com"
export QSTAT_HEADER="JobId:User:QueuedTime:RunTime:WallTime:State:Location:Nodes"
export TZ="America/New_York"
export EDITOR="vi"

# Clusters
export BRIDGES='vpuri1@bridges2.psc.edu:/ocean/projects/eng17006p/vpuri1'
export UIUC='vpuri3@linux.ews.illinois.edu:/home/vpuri3'

## num of CPU cores
# export NCORES=$(julia -e 'Sys.cpu_info() |> length |> print')
# export NCORES=$(python3 -c 'import psutil; print(psutil.cpu_count(logical=False))')
export NPROCS=$(python3 -c 'import os; print(os.cpu_count())')

# NEK
export NEK_WD=$HOME'/Nek5000/run'

ME=$(whoami)
case `uname` in
Darwin)
    export NPROCS=$(sysctl -n hw.ncpu)
	MACHINE="MBP"

	#Ensure user-installed binaries take precedence
	export PATH=/usr/local/bin:$PATH

	## homebrew
	export PATH=/usr/local/sbin:$PATH

	# MATLAB
	export MTLB_BIN=/Applications/MATLAB_R2022b.app/bin

	# NEK
	export NEK_WD=$HOME'/Nek5000/run'

    # python
    # export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.7/site-packages

	;;
Linux)
	MACHINE=$(hostname)

    # python tooling
	export PATH=$HOME/.local/bin:$PATH

	;;
esac

# Julia
export JULIA_DEPOT_PATH="$HOME/.julia"
# export JULIA_NUM_THREADS=$NPROCS 
export JULIA_NUM_PRECOMPILE_TASKS=$NPROCS
# export JULIA_CUDA_MEMORY_POOL=none
#
