#!/bin/bash

# util
alias     cp='cp -r'
alias    scp='scp -r'
alias    ssh='ssh -Y'
alias     ..='cd ..'
alias     dc='cd -'
alias    cdn='cd $WD; s'
alias    cdg='cd $HOME/Google\ Drive; s'
alias    cdd='cd $HOME/Downloads; s'
alias    cdm='cd $HOME/matlab; s'
alias    cdj='cd $JULIA_DEPOT_PATH/dev; s'
#alias     pb='pbcopy'
#alias     bc='pbpaste'
alias     kk='kill'
alias     ka='killall'
alias     k9='kill -9'
alias     tc='tar -cvf'  # tar create
alias     tx='tar -xvf'  # tar extract
alias     hn='head -n'   #
alias    hn1='head -n 1' # tar extract
# 
alias     em='emacs -nw'
alias     tm='tmux -new'
alias   mtlb='$MTLB_BIN/matlab -nodesktop'
alias     qs='qstat  -u $(whoami)' 
alias     sq='squeue -u $(whoami)' 
alias     tf='tail -f'
alias     le='less'
alias    lel='less logfile'
# git
alias     gs='git status'
alias     gb='git branch'
alias  gdiff='git diff'
alias    gdf='git difftool'
# screen
alias    sls='screen -ls'
alias    sdr='screen -dr'
#. $HOME/Downloads/z-master/z.sh

case `uname` in
Darwin)
	# util
	alias      s='ls -lh  -G'
	alias     la='ls -lA  -G'
	alias     lt='ls -ltr -G'
	alias    cdv='cd $HOME/vedant; s'
	# osx
    alias   disp='open /System/Library/PreferencePanes/Displays.prefPane'
    alias   opcr='open -a /Applications/Google\ Chrome.app/'
    # brew
    alias     bu='brew upgrade; brew update'
    alias   bdep='brew deps --tree'
	;;
Linux)
	# util
	alias  s='ls -lh  --color=tty'
	alias la='ls -lA  --color=tty'
	alias lt='ls -ltr --color=tty'
	;;
esac
