"
set omnifunc=syntaxcomplete#Complete

set nocompatible
set autoread

set noerrorbells

set fileformat=unix
set encoding=utf-8

au BufRead .gitconfig,gitconfig setf make
au BufRead SIZE  setf fortran " nek
au BufRead *.usr setf fortran " nek
au BufRead *.geo setf c       " gmsh

autocmd FileType make    set tabstop=2 shiftwidth=8 softtabstop=0
autocmd FileType fortran set tabstop=2 shiftwidth=2 softtabstop=2

set path+=**
set wildmenu

highlight Visual ctermfg=Black ctermbg=Yellow cterm=NONE
